// <auto-generated />
using System;
using AssetManagement.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetManagement.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106091013_Add_New_Entities_And_Relationships")]
    partial class Add_New_Entities_And_Relationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<int>("AssetObjectiveId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetObjectiveId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LifecycleStage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskRating")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.AssetObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ObjectiveText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganisationalObjectiveId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationalObjectiveId");

                    b.ToTable("AssetObjectives");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.AuditFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("integer");

                    b.Property<string>("ClauseReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DecisionRecordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("DecisionRecordId");

                    b.ToTable("AuditFindings");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.DataAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataQuality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InformationSystemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InformationSystemId");

                    b.ToTable("DataAssets");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.DecisionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuditFindingId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuditFindingId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AssetId");

                    b.HasIndex("AuditFindingId1");

                    b.ToTable("DecisionRecords");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.InformationSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InformationSystems");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.OrganisationalObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrganisationalObjectives");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.PredictiveAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DecisionRecordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DecisionRecordId");

                    b.ToTable("PredictiveActions");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.RiskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssetId")
                        .HasColumnType("integer");

                    b.Property<double>("Impact")
                        .HasColumnType("double precision");

                    b.Property<double>("Likelihood")
                        .HasColumnType("double precision");

                    b.Property<string>("MitigationPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AssetId");

                    b.ToTable("RiskItems");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.Activity", b =>
                {
                    b.HasOne("AssetManagement.DataAccess.Entities.Asset", "Asset")
                        .WithMany("Activities")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.DataAccess.Entities.AssetObjective", "AssetObjective")
                        .WithMany("Activities")
                        .HasForeignKey("AssetObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssetObjective");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.AssetObjective", b =>
                {
                    b.HasOne("AssetManagement.DataAccess.Entities.OrganisationalObjective", "OrganisationalObjective")
                        .WithMany("AssetObjectives")
                        .HasForeignKey("OrganisationalObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganisationalObjective");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.AuditFinding", b =>
                {
                    b.HasOne("AssetManagement.DataAccess.Entities.Asset", "Asset")
                        .WithMany("AuditFindings")
                        .HasForeignKey("AssetId");

                    b.HasOne("AssetManagement.DataAccess.Entities.DecisionRecord", "DecisionRecord")
                        .WithMany("AuditFindings")
                        .HasForeignKey("DecisionRecordId");

                    b.Navigation("Asset");

                    b.Navigation("DecisionRecord");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.DataAsset", b =>
                {
                    b.HasOne("AssetManagement.DataAccess.Entities.InformationSystem", "InformationSystem")
                        .WithMany("DataAssets")
                        .HasForeignKey("InformationSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformationSystem");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.DecisionRecord", b =>
                {
                    b.HasOne("AssetManagement.DataAccess.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("AssetManagement.DataAccess.Entities.Asset", "Asset")
                        .WithMany("DecisionRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.DataAccess.Entities.AuditFinding", "AuditFinding")
                        .WithMany()
                        .HasForeignKey("AuditFindingId1");

                    b.Navigation("Activity");

                    b.Navigation("Asset");

                    b.Navigation("AuditFinding");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.PredictiveAction", b =>
                {
                    b.HasOne("AssetManagement.DataAccess.Entities.DecisionRecord", "DecisionRecord")
                        .WithMany("PredictiveActions")
                        .HasForeignKey("DecisionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionRecord");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.RiskItem", b =>
                {
                    b.HasOne("AssetManagement.DataAccess.Entities.Activity", "Activity")
                        .WithMany("RiskItems")
                        .HasForeignKey("ActivityId");

                    b.HasOne("AssetManagement.DataAccess.Entities.Asset", "Asset")
                        .WithMany("RiskItems")
                        .HasForeignKey("AssetId");

                    b.Navigation("Activity");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.Activity", b =>
                {
                    b.Navigation("RiskItems");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.Asset", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AuditFindings");

                    b.Navigation("DecisionRecords");

                    b.Navigation("RiskItems");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.AssetObjective", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.DecisionRecord", b =>
                {
                    b.Navigation("AuditFindings");

                    b.Navigation("PredictiveActions");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.InformationSystem", b =>
                {
                    b.Navigation("DataAssets");
                });

            modelBuilder.Entity("AssetManagement.DataAccess.Entities.OrganisationalObjective", b =>
                {
                    b.Navigation("AssetObjectives");
                });
#pragma warning restore 612, 618
        }
    }
}
